trigger:
- master

resources:
  repositories:
  - repository: templates
    type: github
    name: JeremyTCD/DevOps.AzurePipelines
    endpoint: JeremyTCD

jobs:
- template: templates/nuget/main.yml@templates
  parameters:
    nugetRestoreEndPoint: "https://pkgs.dev.azure.com/JeremyTCD/_packaging/Main/nuget/v2"
    nugetRestorePat: "$(nugetRestorePat)"
    nugetPushEndpoint: "https://pkgs.dev.azure.com/JeremyTCD/_packaging/Main/nuget/v2"
    runInheritDoc: false
    runTests: false