trigger:
- master

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

resources:
  repositories:
  - repository: templates
    type: github
    name: JeremyTCD/DevOps.AzurePipelines
    endpoint: JeremyTCD

jobs:
- template: nuget-package.yml@templates
  parameters:
    nugetRestoreEndPoint: "https://pkgs.dev.azure.com/JeremyTCD/_packaging/Main/nuget/v2"
    nugetPushEndpoint: "https://pkgs.dev.azure.com/JeremyTCD/_packaging/Main/nuget/v2"
    runInheritDoc: false
    runTests: false