trigger:
- master

resources:
  repositories:
  - repository: templates
    type: github
    name: JeringTech/DevOps.AzurePipelines
    endpoint: JeremyTCD

jobs:
- template: templates/nuget/main.yml@templates
  parameters:
    nugetReleasePushEndpoint: "https://pkgs.dev.azure.com/JeremyTCD/_packaging/Main/nuget/v2"
    runInheritDoc: false
    runTests: false
